###
### A complete description of a Prefect Deployment for flow 'parent'
###
name: python
description: deployment using s3 storage
version: snapshot
# The work queue that will handle this deployment's runs
work_queue_name: default
work_pool_name: kubes-pool
tags:
- s3
parameters: {}
schedule: null
is_schedule_active: true
infra_overrides:
  image: prefect-registry:5000/flow:latest
  image_pull_policy: Always
  customizations:
  - op: add
    path: /spec/template/spec/containers/0/env/-
    value:
      name: AWS_ACCESS_KEY_ID
      valueFrom:
        secretKeyRef:
          name: minio
          key: root-user
  - op: add
    path: /spec/template/spec/containers/0/env/-
    value:
      name: AWS_SECRET_ACCESS_KEY
      valueFrom:
        secretKeyRef:
          name: minio
          key: root-password
  service_account_name: prefect-flows
  finished_job_ttl: 300
infrastructure:
  type: kubernetes-job
  env: {}
  labels: {}
  name: null
  command: null
  image: prefecthq/prefect:2.18.0-python3.10
  namespace: default
  service_account_name: null
  image_pull_policy: null
  cluster_config: null
  job:
    apiVersion: batch/v1
    kind: Job
    metadata:
      labels: {}
    spec:
      template:
        spec:
          parallelism: 1
          completions: 1
          restartPolicy: Never
          containers:
          - name: prefect-job
            env: []
  customizations: []
  job_watch_timeout_seconds: null
  pod_watch_timeout_seconds: 60
  stream_output: true
  finished_job_ttl: null
  block_type_slug: kubernetes-job
  _block_type_slug: kubernetes-job

###
### DO NOT EDIT BELOW THIS LINE
###
flow_name: parent
manifest_path: null
storage:
  bucket_path: minio-flows
  aws_access_key_id: null
  aws_secret_access_key: null
  _block_document_id: 2cbe5e7d-f5a3-425d-99a2-b0425c4c7e15
  _block_document_name: minio-flows
  _is_anonymous: false
  block_type_slug: s3
  _block_type_slug: s3
path: parent
entrypoint: flows/parent_flow.py:parent
parameter_openapi_schema:
  title: Parameters
  type: object
  properties: {}
  required: null
  definitions: null
timestamp: '2023-12-02T10:07:39.428634+00:00'
triggers: []
enforce_parameter_schema: null
