###
### A complete description of a Prefect Deployment for flow 'greetings'
###
name: dask
description: dask kubes
version: snapshot
# The work queue that will handle this deployment's runs
work_queue_name: default
work_pool_name: default-agent-pool
tags: []
parameters:
  names:
  - arthur
  - trillian
  - ford
  - marvin
schedule: null
is_schedule_active: null
infra_overrides:
  image: prefect-registry:5000/flow:latest
  service_account_name: prefect-flows
  finished_job_ttl: 300
infrastructure:
  type: kubernetes-job
  env: {}
  labels: {}
  name: null
  command: null
  image: prefecthq/prefect:2.10.21-python3.10
  namespace: default
  service_account_name: null
  image_pull_policy: null
  cluster_config: null
  job:
    apiVersion: batch/v1
    kind: Job
    metadata:
      labels: {}
    spec:
      template:
        spec:
          parallelism: 1
          completions: 1
          restartPolicy: Never
          containers:
          - name: prefect-job
            env: []
  customizations: []
  job_watch_timeout_seconds: null
  pod_watch_timeout_seconds: 60
  stream_output: true
  finished_job_ttl: null
  block_type_slug: kubernetes-job
  _block_type_slug: kubernetes-job

###
### DO NOT EDIT BELOW THIS LINE
###
flow_name: greetings
manifest_path: null
storage: null
path: /opt/prefect/flows
entrypoint: flows/dask_kubes_flow.py:greetings
parameter_openapi_schema:
  title: Parameters
  type: object
  properties:
    names:
      title: names
      position: 0
      type: array
      items:
        type: string
  required:
  - names
  definitions: null
timestamp: '2023-07-14T03:21:09.670449+00:00'
triggers: []
