apiVersion: v1
kind: Service
metadata:
  name: ray-lb
spec:
  type: LoadBalancer
  ports:
  - name: client
    port: 10001
    protocol: TCP
    targetPort: 10001
  - name: dashboard
    port: 8265
    protocol: TCP
    targetPort: 8265
  - name: gcs
    port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    ray.io/cluster: raycluster-complete
    ray.io/node-type: head
