# see https://github.com/PrefectHQ/prefect-helm/tree/main/charts/prefect-agent
agent:
  image:
    prefectTag: 2.10.20-python3.9

  config:
    workPool: default-agent-pool

  apiConfig: server

  serverApiConfig:
    apiUrl: http://prefect-server:4200/api
