# see https://github.com/PrefectHQ/prefect-helm/tree/main/charts/prefect-server
server:
  image:
    prefectTag: 2.10.21-python3.10

postgresql:
  # use sqlite instead
  enabled: false
  useSubChart: false
