# see https://github.com/PrefectHQ/prefect-helm/tree/main/charts/prefect-agent
agent:
  image:
    prefectTag: 2.18.0-python3.10

  config:
    workPool: default-agent-pool

  apiConfig: server

  serverApiConfig:
    apiUrl: http://prefect-server:4200/api
